#!/bin/bash
# PreToolUse hook: warn before editing the GENERATED docker-compose.yml in homelab-maestro.
# The root compose file is built by scripts/build_compose_file.sh — hand edits will be overwritten.

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

# Normalize to catch relative and absolute paths
case "$FILE_PATH" in
  */homelab-maestro/docker-compose.yml)
    cat <<'EOF'
{
  "hookSpecificOutput": {
    "hookEventName": "PreToolUse",
    "permissionDecision": "deny",
    "permissionDecisionReason": "homelab-maestro/docker-compose.yml is GENERATED by scripts/build_compose_file.sh. Edit the source fragments in compose/ instead, then run the build script."
  }
}
EOF
    exit 0
    ;;
esac
